### PR TITLE
UBO-170 Added preview and feedback buttons

### PR DESCRIPTION
**Pull request by Possommi**

### CODE REVIEW

**Review by fluetze — COMMENTED** [review]
Why the javascript? Building the mailto url could be implemented in XSL too.

**Comment by Possommi** [comment]
> Why the javascript? Building the mailto url could be implemented in XSL too.

This way the function can be easily assigned to another ui element, but I do not mind to implement this feature in xsl.

**Review by fluetze — COMMENTED** [review]
I'd prefer if all button targets are built the same way, so if there is no need for JS, just build them in-place via xsl.

**Comment by Possommi** [comment]
> I'd prefer if all button targets are built the same way, so if there is no need for JS, just build them in-place via xsl.

@fluetze I replaced JS by xsl.

**Review by fluetze — APPROVED** [review]

**Pull request merged**
