### PR TITLE
UBO-286 Add authorityURI and valueURI to mods:genre in postprocessing…

### PR DESCRIPTION
**Pull request by Possommi**
… to enable class mapping
[UBO-286](https://mycore.atlassian.net/browse/UBO-286)

[UBO-286]: https://mycore.atlassian.net/browse/UBO-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by fluetze — CHANGES_REQUESTED** [review]
I cannot approve this. 

1.
@valueURI is redundant to the content node of the genreelement.

2.
This xsl is the only xsl that adds authority and value URI to mods:genre[@type='intern']. All other templates will ignore this value/authority uri and just rely on the @type='intern'. Please see all other XSLs in UBO. Additionally, none of our existing stored objects contain those authority/value URIs.

3.
Line 72 ff of MCRClassMapper controls how mods elements map to classifications.
Authority and value attributes are not the only way. May be we should add something here, or otherwise, we should modify -all- code handling mods:genre, and migrate all metadata.

**Comment by Possommi** [comment]
> I cannot approve this.
> 
> 
> @valueURI is redundant to the content node of the genreelement.
> 
> 
> This xsl is the only xsl that adds authority and value URI to mods:genre[@type='intern']. All other templates will ignore this value/authority uri and just rely on the @type='intern'. Please see all other XSLs in UBO. Additionally, none of our existing stored objects contain those authority/value URIs.
> 
> 
> Line 72 ff of MCRClassMapper controls how mods elements map to classifications. Authority and value attributes are not the only way. May be we should add something here, or otherwise, we should modify -all- code handling mods:genre, and migrate all metadata.

what about automatically creating a ```mods:classification``` element in postprocessing?

**Comment by fluetze** [comment]
It is a mods:genre and should stay to be a mods:genre.

It is also a mods:genre in MIR.

 

Von: Possommi ***@***.***> 
Gesendet: Donnerstag, 7. Dezember 2023 09:36
An: MyCoRe-Org/ubo ***@***.***>
Cc: Lützenkirchen, Frank ***@***.***>; Review requested ***@***.***>
Betreff: Re: [MyCoRe-Org/ubo] UBO-286 Add authorityURI and valueURI to mods:genre in postprocessing… (PR #338)

 

I cannot approve this.

@valueURI is redundant to the content node of the genreelement.

This xsl is the only xsl that adds authority and value URI to ***@***.*** <https://github.com/type> ='intern']. All other templates will ignore this value/authority uri and just rely on the @type <https://github.com/type> ='intern'. Please see all other XSLs in UBO. Additionally, none of our existing stored objects contain those authority/value URIs.

Line 72 ff of MCRClassMapper controls how mods elements map to classifications. Authority and value attributes are not the only way. May be we should add something here, or otherwise, we should modify -all- code handling mods:genre, and migrate all metadata.

what about automatically creating a mods:classification element in postprocessing?

**Comment by Possommi** [comment]
I suggest migrating existing mods:genre elements to mods:genre with authorityURI and valueURI and adjusting editors and stylesheets, just like in MIR. We should discuss that issue soon, as we need a proper solution for mapping the genre of ubo to orcid work types

**Pull request closed without merging**
