### PR TITLE
UBO-338 Improved indexing of corresponding author

### PR DESCRIPTION
**Pull request by Possommi**
[UBO-338](https://mycore.atlassian.net/browse/UBO-338)

[UBO-338]: https://mycore.atlassian.net/browse/UBO-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by fluetze — CHANGES_REQUESTED** [review]
The whole template needs refactoring.

It all starts with 
`<xsl:apply-templates select="descendant::mods:name[@type='personal']/mods:role/mods:roleTerm[@type='code']" mode="solrField" />`

The "descendant::" will cause those fields to be built also for included relatedItems that are NOT type host. Do we really want that?
And the ../../mods:role/mods:roleTerm will go "up", whatever that "up" is - may be even not a host-child relation.

**Comment by Possommi** [comment]
> The whole template needs refactoring.
> 
> It all starts with `<xsl:apply-templates select="descendant::mods:name[@type='personal']/mods:role/mods:roleTerm[@type='code']" mode="solrField" />`
> 
> The "descendant::" will cause those fields to be built also for included relatedItems that are NOT type host. Do we really want that? And the ../../mods:role/mods:roleTerm will go "up", whatever that "up" is - may be even not a host-child relation.

What `mods:roleTerms` should be considered, what was the reason for using the `descendant::mods:name`axis in the first place?

**Comment by Possommi** [comment]
@kponten Could you please advice.

**Comment by fluetze** [comment]
> > The whole template needs refactoring.
> > It all starts with `<xsl:apply-templates select="descendant::mods:name[@type='personal']/mods:role/mods:roleTerm[@type='code']" mode="solrField" />`
> > The "descendant::" will cause those fields to be built also for included relatedItems that are NOT type host. Do we really want that? And the ../../mods:role/mods:roleTerm will go "up", whatever that "up" is - may be even not a host-child relation.
> 
> What `mods:roleTerms` should be considered, what was the reason for using the `descendant::mods:name`axis in the first place?

The reason was to index mods:name's located in relatedItem[@type='host|series'] too, I think. But that was before we introduced other relation types. So we need to define and agree upon what metadata from related items should be found/indexed for a publication.

**Comment by kkrebs** [comment]
perhaps we should solve this with a separate template and not include in an existing one? Like:
<xsl:apply-templates select="mods:name[@type='personal']/mods:role/mods:roleTerm[text()='corresponding_author']" ...

**Comment by kponten** [comment]
In my opinion, only the role in the genre should be relevant for the search for the CA. CAs from a relatedItem should not be indexed.

**Review by fluetze — APPROVED** [review]

**Pull request merged**
